---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bkroger-test.fullname" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bkroger-test.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bkroger-test.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "bkroger-test.fullname" . }}
  apiGroup: rbac.authorization.k8s.io