name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - app/frontend/src/**
      - Dockerfile

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Build the Docker image
      run: docker buildx build -t my-image .